services:
  medlibre-gpt-ollama:
    container_name: medlibre-gpt-ollama
    image: medlibre-gpt-openai-ollama
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.ollama_and_openai
    ports:
      - 7001:7080
    environment:
      PORT: 7080
      PGPT_PROFILES: ollama
      PGPT_MODE: ollama
      PGPT_OLLAMA_API: http://176.9.101.2:11434
      PGPT_OLLAMA_LLM_MODEL: meditron:70b
      PGPT_OLLAMA_EMBEDDING_MODEL: nomic-embed-text