services:
  medlibreGPT:
    container_name: medlibre-gpt
    image: medlibre-gpt
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: local
      PGPT_MODE: local

