services:
  medlibre-gpt-ollama:
    container_name: medlibre-gpt-ollama
    image: medlibre-gpt-openai-ollama
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.ollama_and_openai
    volumes:
      - ./local_data/:/home/app/local_data
    ports:
      - 7001:7080
    environment:
      PORT: 7080
      PGPT_PROFILES: ollama
      PGPT_MODE: ollama
      PGPT_OLLAMA_API: http://34.159.66.151:11434
      PGPT_OLLAMA_LLM_MODEL: mixtral:8x7b
      PGPT_OLLAMA_EMBEDDING_MODEL: nomic-embed-text
      PGPT_OLLAMA_REQUEST_TIMEOUT: 600.0
      LOCAL_INGESTION_ENABLED: true