# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 4096
  context_window: 8000
  tokenizer: BioMistral/BioMistral-7B
  prompt_style: "mistral"

llamacpp:
  llm_hf_repo_id: MaziyarPanahi/BioMistral-7B-GGUF
  llm_hf_model_file: BioMistral-7B.Q4_K_M.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: NeuML/pubmedbert-base-embeddings

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
