# Using ollama and postgres for the vector, doc and index store. Ollama is also used for embeddings.
# To use install these extras:
# poetry install --extras "llms-ollama ui vector-stores-postgres embeddings-ollama storage-nodestore-postgres"
server:
  env_name: ${APP_ENV:ollama}

llm:
  mode: ollama
  max_new_tokens: 512
  context_window: 3900

embedding:
  mode: ollama
  embed_dim: 768

ollama:
  llm_model: mistral
  embedding_model: nomic-embed-text
  api_base: http://localhost:11434

nodestore:
  database: postgres

vectorstore:
  database: postgres

postgres:
  host: localhost
  port: 5432
  database: postgres
  user: postgres
  password: admin
  schema_name: private_gpt


#postgres:
#  host: ${PGPT_POSTGRES_HOST}
#  port: ${PGPT_POSTGRES_PORT}
#  database: ${PGPT_POSTGRES_DATABASE}
#  user: ${PGPT_POSTGRES_USER}
#  password: ${PGPT_POSTGRES_PASSWORD}
#  schema_name: ${PGPT_POSTGRES_DATABASE_SCHEMA}