# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 4000
  context_window: 8000
  tokenizer: mistralai/Mixtral-8x7B-Instruct-v0.1

llamacpp:
  prompt_style: "mistral"
  llm_hf_repo_id: TheBloke/Mixtral-8x7B-v0.1-GGUF
  llm_hf_model_file: mixtral-8x7b-v0.1.Q4_K_M.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant