llm:
  mode: openai

openai:
  model: gpt-4-1106-preview # Optional model to use. Default is "gpt-3.5-turbo"
                               # Note: Open AI Models are listed here: https://platform.openai.com/docs/models
