# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: mistralai/Mixtral-8x7B-Instruct-v0.1
  prompt_style: "mistral"

llamacpp:
  llm_hf_repo_id: TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mixtral-8x7b-instruct-v0.1.Q6_K.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: nomic-ai/nomic-embed-text-v1.5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
