# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 4000
  context_window: 8000
  tokenizer: TheBloke/meditron-7B-GPTQ

llamacpp:
  prompt_style: "default"
  llm_hf_repo_id: TheBloke/meditron-7B-GGUF
  llm_hf_model_file: meditron-7b.Q5_K_S.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant