# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: epfl-llm/meditron-70b
  prompt_style: "llama2"

llamacpp:
  llm_hf_repo_id: TheBloke/meditron-70B-GGUF
  llm_hf_model_file: meditron-70b.Q3_K_M.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: nomic-ai/nomic-embed-text-v1.5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
