# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 4096
  context_window: 8000
  tokenizer: mistralai/Mixtral-8x7B-Instruct-v0.1
  prompt_style: "mistral"

llamacpp:
  llm_hf_repo_id: MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-GGUF
  llm_hf_model_file: Mixtral-8x22B-Instruct-v0.1.Q4_K_M-00001-of-00002.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: BAAI/bge-m3

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
